Carousel
cusec/2022 pull request #19
Opened 2021-09-25 03:22 UTC by charyung

- [ ] Responsive
- [ ] Accessible

2021-10-06 04:50 UTC, itsflores requested changes

2021-10-06 04:50 UTC, itsflores commented on src/sections/descriptions/descriptions.js
> +                    <Slider className="h-full flex items-center" classNameTray="h-full w-full" classNameTrayWrap="h-full">
This needs some margin at the top, maybe 84px? smaller on mobile?

2021-10-06 04:50 UTC, itsflores commented on src/sections/descriptions/descriptions.js
> +                                <A lineColour="var(--light)">Stats from last year</A>
These should be h2, or if they're links should be bigger

2021-10-09 04:53 UTC, yungchar commented on src/sections/descriptions/descriptions.js
> +                    <Slider className="h-full flex items-center" classNameTray="h-full w-full" classNameTrayWrap="h-full">
It looks kind of packed on short desktop screens (like the one I have) with that much space because it's hard to fit the logo at the bottom onto the screen as well:
![image](https://user-images.githubusercontent.com/32499385/136644195-b7feca07-21ba-426a-a5e8-affcea60a3c2.png)

How do you feel about this? 48px
![image](https://user-images.githubusercontent.com/32499385/136644551-b6b0e940-ce70-4993-9e74-b4bcf4e60f6e.png)

2021-10-09 06:11 UTC, itsflores approved these changes

2021-10-09 15:11 UTC, merged